### ISSUE TITLE
Different result when defining the polynomial

### ISSUE THREAD

**Issue by javicarron** [pjabardo/Jacobi.jl#12]
I am new to Julia so maybe I am just doing something wrong, but I was having some unexpected behavior.
In particular, the value produced by evaluating the `jacobi` function is not the same than getting the polynomial and evaluating it.

```julia
julia> jacobi(0.5, 100, 0, 0)
-0.06051802596186111

julia> pol = poly_jacobi(100, 0, 0)
julia> pol(0.5)
-1512.3404729900394
```

My guess is that this is a rounding error, but I also get different values if I use 0.5 as a `BigFloat`, so I am not sure.

In my usecase, I need to integrate the product of several different jacobi polynomials (and multiplied by other factors), so I think it would be more efficient to have the polynomial and evaluate it several times, rather than recalculating all weights in every evaluation, but maybe this is not possible for high-order polynomials.

**Comment by pjabardo** [comment]
The problem is that when you call poly_jacobi, the code assumes that the coefficients are Float64. You should specify the polynomial coefficients types:

```julia
julia> pol = poly_jacobi(100, 0, 0, BigFloat);

julia> pol(0.5)
-0.0605180259618611868746542950522465670931308111444525052411846977435450946493452

julia> pol(0.5) - jacobi(big"0.5", 100)
1.493949127584894931791840216203129715573122465311015076120535041198677472218059e-59
```

I hope this helps. I will try to make this clearer on the docs

Thank you for bringing me this

Paulo

**Comment by pjabardo** [comment]
I just noticed that this is not in the docs. And that is bad. I will try to overhaul the docs this weekend. I wrote much of this code long ago and there is almost no inline docs.

**Comment by javicarron** [comment]
I see, thank you for quick reply, this solves my problem.

**Comment by pjabardo** [comment]
The new version has improved documentation
