### ISSUE TITLE
Support n>=170

### ISSUE THREAD

**Issue by eschnett** [pjabardo/Jacobi.jl#4]
I tried to call `wglj` with `n=170`, and this returns all zeros. Smaller polynomial orders seem to work fine.

Looking at the code, the culprit seem to be the calls to `gamma` in `gauss_quad.jl`. The Gamma function returns very large values and can easily overflow:
```Julia
    coef = 2^(a+b+1) / (Q-o) * (gamma(a+Q) / gamma(Q*o)) * (gamma(b+Q) / gamma(a+b+Q+1))
```

It should be possible to replace `gamma(x) / gamma(y)` by calls to `lgamma`, which does not overflow, as in `exp(lgamma(x) - lgamma(y))`, since we know that the result will not overflow.

**Comment by MikaelSlevinsky** [comment]
Have you seen the package https://github.com/ajt60gaibb/FastGaussQuadrature.jl?
