### ISSUE TITLE
jacobi function does not accept an array

### ISSUE THREAD

**Issue by johnbcoughlin** [pjabardo/Jacobi.jl#7]
From the doc on the `jacobi` function: 

```
 * `jacobi(x, n, a, b) where `x` is an array
```

However:

```
julia> Jacobi.jacobi([1., 2., 3.], 4, 1, 1)
ERROR: MethodError: no method matching one(::Array{Float64,1})
```

The docs should be changed to note where broadcasting is required.

**Comment by pjabardo** [comment]
Sorry for the extreme tardiness. I removed the array functions once the dot functionality was available. Now, 
use 

> Jacobi.jacobi.([1., 2., 3.], 4, 1, 1)

for arrays. I will clean up the docs.

Again sorry

**Comment by pjabardo** [comment]
If people really want the array versions I can put it back. But for now I am closing this issue
